### PR TITLE
Change dependency from JWT to JWTAuth to work with newer version

### PR DESCRIPTION
**Pull request by VegardSkui**

### CODE REVIEW

**Comment by VegardSkui** [comment]
I forgot to push a change in JwtAuthGuardServiceProvider, it should say $app['tymon.jwt.auth']. Please just have a look at the changes in this pull request to fix the package.

**Comment by irazasyed** [comment]
Thanks for the PR. Have you tested this?

**Comment by VegardSkui** [comment]
Yes, I'm using this in a personal project. You may download and double-check it before merging to be absolutely certain.

**Comment by irazasyed** [comment]
Well, I don't have a project right now to test this out. But i hope it works fine. I've merged it for now. Will revert if things aren't working well.

**Comment by VegardSkui** [comment]
Yeah, this pull request fixes issues in specific version, don't now about the dev, but at least it works in production versions for now. Just revert it if you have to! :smile:

**Pull request merged**
